<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Methodology and Results – STAT515 Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e83117e711fad372bcb8c8022997a9a8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STAT515 Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about_us.html"> 
<span class="menu-text">About Us</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./introduction.html"> 
<span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./research_questions.html"> 
<span class="menu-text">Research Questions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./results.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./conclusion.html"> 
<span class="menu-text">Conclusion</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./codes.html"> 
<span class="menu-text">Codes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./references.html"> 
<span class="menu-text">References</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#methodology" id="toc-methodology" class="nav-link active" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Methodology and Results</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this page, We shall discuss the methodology used in our project and discuss the findings and results.</p>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<section id="i.-selection-of-dataset" class="level4">
<h4 class="anchored" data-anchor-id="i.-selection-of-dataset">I. SELECTION OF DATASET</h4>
<p>In this project, We first selected our dataset from the 2021-2023 NHANES dataset. We then chose the following variables from the sub-datasets.</p>
<ol type="1">
<li><p><strong><em>DEMO_L (demographic dataset)</em></strong></p>
<ol type="1">
<li><p><strong>SEQN</strong> → unique ID;</p></li>
<li><p><strong>RIDAGEYR</strong> → age in years;</p></li>
<li><p><strong>RIAGENDR</strong> → sex (1=male, 2=female);</p></li>
<li><p><strong>RIDRETH3</strong> → race/ethnicity;</p></li>
<li><p><strong>INDFMPIR</strong> → income-to-poverty ratio;</p></li>
<li><p><strong>DMDMARTZ</strong> → marital status;</p></li>
<li><p><strong>DMDEDUC2</strong> → education level;</p></li>
</ol></li>
</ol>
<p>These are predictors for chronic diseases.</p>
<ol start="2" type="1">
<li><p><strong><em>BMX_L (BMI/ Body measurements)</em></strong></p>
<ol type="1">
<li><p><strong>BMXWT</strong> → weight</p></li>
<li><p><strong>BMXHT</strong> → height</p></li>
<li><p><strong>BMXBMI</strong> → BMI (body mass index)</p></li>
<li><p><strong>BMXWAIST</strong> → waist circumference</p></li>
</ol></li>
</ol>
<p>These variables are important as they are major risk factors for diabetes, hypertension, and heart disease.</p>
<ol start="3" type="1">
<li><p><strong><em>BPXO_L (Blood pressure)</em></strong></p>
<ol type="1">
<li><p><strong>OSBP</strong> → systolic BP</p></li>
<li><p><strong>ODBP</strong> → diastolic BP</p></li>
<li><p><strong>OSBPA</strong>, <strong>ODBPA</strong> → averaged readings</p></li>
</ol></li>
</ol>
<p>These variables are important because blood pressure is a chronic disease indicator and a strong predictor for cardiovascular risk.</p>
<ol start="4" type="1">
<li><p><strong><em>GHB_L (Glycohemaglobin)</em></strong></p>
<ol type="1">
<li><strong>LBXGH</strong> → HbA1c (%)</li>
</ol></li>
</ol>
<p>This variable is used to detect diabetes.</p>
<ol start="5" type="1">
<li><p><strong><em>TCHOL_L (Total cholesterol)</em></strong></p>
<ol type="1">
<li><strong>LBXTC</strong> → total cholesterol (mg/dL)</li>
</ol></li>
</ol>
<p>This variable is a chronic disease predictor</p>
<ol start="6" type="1">
<li><p><strong><em>DIQ_L (diabetes questionnaire)</em></strong></p>
<ol type="1">
<li><p><strong>DIQ010</strong> → “Doctor diagnosed diabetes?” (1=yes/ 2=no)</p></li>
<li><p><strong>DIQ160</strong> → “Borderline diabetes?”</p></li>
<li><p><strong>DIQ050</strong> → taking insulin?</p></li>
</ol></li>
</ol>
<p>This variable gives the main binary outcome for logistic regression.</p>
<ol start="7" type="1">
<li><p><strong><em>SMQ_L (smoking questionnaire)</em></strong></p>
<ol type="1">
<li><strong>SMQ020</strong> → smoked at least 100 cigarettes</li>
</ol></li>
</ol>
<p>This variable is useful because smoking is a huge risk factor for many diseases and is a strong predictor.</p>
<p>* We limited our dataset to include only adults (20 years and above) as major health risks are more likely to occur in them and including children could cause biases.</p>
</section>
<section id="ii.-setting-up-dataset-in-rstudio" class="level4">
<h4 class="anchored" data-anchor-id="ii.-setting-up-dataset-in-rstudio">II. Setting up dataset in RStudio</h4>
<p>After converting the .xpt file to a csv file using the “haven”. We cleaned up our data and selected only the important variables which will be used during the project.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'haven' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"nhanes_2021_2023_chronic_disease.csv"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    SEQN SDDSRVYR RIDSTATR RIAGENDR RIDAGEYR RIDAGEMN RIDRETH1 RIDRETH3
1 130378       12        2        1       43       NA        5        6
2 130379       12        2        1       66       NA        3        3
3 130380       12        2        2       44       NA        2        2
4 130384       12        1        1       43       NA        1        1
5 130385       12        1        2       65       NA        3        3
6 130386       12        2        1       34       NA        1        1
  RIDEXMON RIDEXAGM DMQMILIZ DMDBORN4 DMDYRUSR DMDEDUC2 DMDMARTZ RIDEXPRG
1        2       NA        2        2        6        5        1       NA
2        2       NA        2        1       NA        5        1       NA
3        1       NA        2        2        6        3        1        2
4       NA       NA        2        2        5        2        3       NA
5       NA       NA        2        1       NA        3        1       NA
6        1       NA        2        1       NA        4        1       NA
  DMDHHSIZ DMDHRGND DMDHRAGZ DMDHREDZ DMDHRMAZ DMDHSEDZ WTINT2YR WTMEC2YR
1        4       NA       NA       NA       NA       NA 50055.45 54374.46
2        2       NA       NA       NA       NA       NA 29087.45 34084.72
3        7       NA       NA       NA       NA       NA 80062.67 81196.28
4        2       NA       NA       NA       NA       NA 15078.75     0.00
5        2       NA       NA       NA       NA       NA 16151.03     0.00
6        3       NA       NA       NA       NA       NA 30995.28 39988.45
  SDMVSTRA SDMVPSU INDFMPIR BMDSTATS BMXWT BMIWT BMXRECUM BMIRECUM BMXHEAD
1      173       2     5.00        1  86.9    NA       NA       NA      NA
2      173       2     5.00        1 101.8    NA       NA       NA      NA
3      174       1     1.41        1  69.4    NA       NA       NA      NA
4      179       2     0.63       NA    NA    NA       NA       NA      NA
5      187       2     5.00       NA    NA    NA       NA       NA      NA
6      179       1     1.33        1  90.6    NA       NA       NA      NA
  BMIHEAD BMXHT BMIHT BMXBMI BMDBMIC BMXLEG BMILEG BMXARML BMIARML BMXARMC
1      NA 179.5    NA   27.0      NA   42.8     NA    42.0      NA    35.7
2      NA 174.2    NA   33.5      NA   38.5     NA    38.7      NA    33.7
3      NA 152.9    NA   29.7      NA   38.5     NA    35.5      NA    36.3
4      NA    NA    NA     NA      NA     NA     NA      NA      NA      NA
5      NA    NA    NA     NA      NA     NA     NA      NA      NA      NA
6      NA 173.3    NA   30.2      NA   42.8     NA    36.2      NA    35.7
  BMIARMC BMXWAIST BMIWAIST BMXHIP BMIHIP BPAOARM BPAOCSZ BPXOSY1 BPXODI1
1      NA     98.3       NA  102.9     NA       R       4     135      98
2      NA    114.7       NA  112.4     NA       R       4     121      84
3      NA     93.5       NA   98.0     NA       R       4     111      79
4      NA       NA       NA     NA     NA    &lt;NA&gt;      NA      NA      NA
5      NA       NA       NA     NA     NA    &lt;NA&gt;      NA      NA      NA
6      NA    106.1       NA  110.6     NA       R       4     110      72
  BPXOSY2 BPXODI2 BPXOSY3 BPXODI3 BPXOPLS1 BPXOPLS2 BPXOPLS3 WTPH2YR.x LBXGH
1     131      96     132      94       82       79       82  56042.13   5.6
2     117      76     113      76       72       71       73  37435.71   5.6
3     112      80     104      76       84       83       77  85328.84   6.2
4      NA      NA      NA      NA       NA       NA       NA        NA    NA
5      NA      NA      NA      NA       NA       NA       NA        NA    NA
6     120      74     115      75       59       64       64  44526.21   5.1
  WTPH2YR.y LBXTC LBDTCSI DIQ010 DID040 DIQ160 DIQ180 DIQ050 DID060 DIQ060U
1  56042.13   264    6.83      2     NA      2      2     NA     NA      NA
2  37435.71   214    5.53      2     NA      2      1     NA     NA      NA
3  85328.84   187    4.84      1     35     NA     NA      2     NA      NA
4        NA    NA      NA      2     NA      2      2     NA     NA      NA
5        NA    NA      NA      2     NA      1      1     NA     NA      NA
6  44526.21   183    4.73      2     NA      2      2     NA     NA      NA
  DIQ070 SMQ020 SMQ040 SMD641 SMD650 SMD100MN SMQ621 SMD630 SMAQUEX2
1     NA      1      3     NA     NA       NA     NA     NA        1
2     NA      1      3     NA     NA       NA     NA     NA        1
3      1      2     NA     NA     NA       NA     NA     NA        1
4     NA      2     NA     NA     NA       NA     NA     NA        1
5      2      2     NA     NA     NA       NA     NA     NA        1
6     NA      1      3     NA     NA       NA     NA     NA        1</code></pre>
</div>
</div>
</section>
<section id="iii.-setting-up-libraries-for-visualization-and-removing-missing-values-and-special-codes." class="level4">
<h4 class="anchored" data-anchor-id="iii.-setting-up-libraries-for-visualization-and-removing-missing-values-and-special-codes.">III. Setting up libraries for visualization and removing missing values and special codes.</h4>
<p>NHANES uses special codes such as “777”, “999”, or “refused”, “NA”. and many more. We cleaned the new dataset to ensure there were no missing or invalid values. We also removed any duplicate values</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'corrplot' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.95 loaded</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Original rows: 7809 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Original columns: 80 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows after removing duplicate: 7809 </code></pre>
</div>
</div>
</section>
<section id="iv.-setting-up-key-health-variables" class="level4">
<h4 class="anchored" data-anchor-id="iv.-setting-up-key-health-variables">IV. Setting up key health variables</h4>
</section>
<section id="v.-conduction-basic-exploratory-analysis" class="level4">
<h4 class="anchored" data-anchor-id="v.-conduction-basic-exploratory-analysis">V. Conduction Basic Exploratory Analysis</h4>
<p>We selected a few variables from the new dataset such as: RIDAGEYR, BMXBMI, BMXWT, BMXHT, BMXWAIST, SBP_mean, DBP_mean, LBXGH, LBXTC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(summary_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    RIDAGEYR         BMXBMI          BMXWT            BMXHT      
 Min.   :20.00   Min.   :11.10   Min.   : 27.90   Min.   :133.0  
 1st Qu.:38.00   1st Qu.:24.70   1st Qu.: 67.50   1st Qu.:159.6  
 Median :56.00   Median :28.50   Median : 79.80   Median :166.5  
 Mean   :53.37   Mean   :29.83   Mean   : 83.28   Mean   :166.9  
 3rd Qu.:68.00   3rd Qu.:33.60   3rd Qu.: 95.40   3rd Qu.:174.2  
 Max.   :80.00   Max.   :74.80   Max.   :248.20   Max.   :200.7  
 NA's   :84      NA's   :1839    NA's   :1853     NA's   :1812   
    BMXWAIST        SBP_mean        DBP_mean          LBXGH       
 Min.   : 60.0   Min.   : 70.0   Min.   : 34.00   Min.   : 3.200  
 1st Qu.: 89.0   1st Qu.:110.7   1st Qu.: 67.33   1st Qu.: 5.200  
 Median : 99.7   Median :120.5   Median : 74.00   Median : 5.500  
 Mean   :101.2   Mean   :123.0   Mean   : 74.70   Mean   : 5.774  
 3rd Qu.:111.5   3rd Qu.:132.7   3rd Qu.: 81.33   3rd Qu.: 5.900  
 Max.   :187.0   Max.   :232.3   Max.   :139.00   Max.   :17.100  
 NA's   :2104    NA's   :1947    NA's   :1949     NA's   :2090    
     LBXTC      
 Min.   : 62.0  
 1st Qu.:159.0  
 Median :185.0  
 Mean   :188.2  
 3rd Qu.:214.0  
 Max.   :438.0  
 NA's   :2318   </code></pre>
</div>
</div>
<p>This statistical summary helps us quickly go through and understand the minimum, maximum and mean values of each variable.</p>
<p>We then created some visualizations to help understand the variables clearly.</p>
<ol type="1">
<li><p>Age Distribution Histogram</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 84 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This histogram helps us visually understand the age range of the individuals in the dataset. As we can see, there are more counts as the age increases.</p></li>
<li><p>BMI Distribution Histogram</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1839 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This histogram shows that the graph is right-skewed. Most of the adults fall between 20 to 40 range.</p></li>
<li><p>Mean SBP histogram</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1947 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
</ol>
<p>This histogram shows a roughly normal distribution between 120 mmHg and 150 mmHg</p>
<ol start="4" type="1">
<li><p>Mean DBP histogram</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1949 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
</ol>
<p>This histogram shows a distribution of the Diastolic blood pressure between 60 mmHg and 90 mmHg.</p>
<ol start="5" type="1">
<li><p>Total Cholesterol Distribution</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2318 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This histogram shows that it peaks around 180-220 mg/dL.</p></li>
<li><p>HbA1c Distribution Histogram</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2090 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
</ol>
<p>This histogram are heavily concentrated between 5% to 6%.</p>
<ol start="7" type="1">
<li><p>Correlation Matrix Heatmap</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The correlation heatmap shows that BMI and waist circumference are strongly correlated, while blood pressure and cholesterol show moderate positive relationships with other metabolic indicators.</p>
</section>
<section id="vi.-answering-research-questions" class="level4">
<h4 class="anchored" data-anchor-id="vi.-answering-research-questions">VI. Answering Research Questions</h4>
<p><strong>(i)</strong> Our first research question explores how BMI influences the risk of diabetes among adults. We first created a binary variable which indicates if a person has diabetes or not (based on the DIQ010 variable), where 1 = Diabetes and 0 = No Diabetes. We also dropped any values which were not available or missing. We then fit a logistic regression model with the diabetes as the response variable and the BMI as the predictor. The aim of this model is to predict if the chances of diabetes increases with BMI.</p>
<p>We also grouped the BMI values into 5 standard categories[3], <strong>Underweight</strong> (less than 18.5), <strong>Normal</strong> (between 18.5 and less than 25), <strong>Overweight</strong> (25 to less than 30), <strong>Obese</strong> ( 30 or greater) and <strong>Severe Obese</strong> (40 or greater).</p>
<p>For each BMI group we calculated the percentage of people with diabetes. We used a bar plot to visualize the result.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ BMXBMI, family = "binomial", data = nhanes_rq1)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -3.612837   0.150813  -23.96   &lt;2e-16 ***
BMXBMI       0.058362   0.004556   12.81   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 4861.3  on 5969  degrees of freedom
Residual deviance: 4702.2  on 5968  degrees of freedom
AIC: 4706.2

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The logistic regression results show that BMI is a statistically significant predictor of diabetes (p &lt; 2e-16). The positive coefficient (0.058) indicates that as BMI increases, the chances of having diabetes also increase. The barplot also helps us easily visualize the increase in the prevalence of diabetes as the BMI increases, with the normal category having a 0.07% chance of diabetes and the severe obese category having a 0.22% chance of diabetes.</p>
<p><strong>(ii)</strong> In our second research question, we explore and try to answer if we can predict diabetes using health risk factors such as BMI, HbA1c, blood pressure, cholesterol, and smoking status.</p>
<p>We selected another subset of variables to fit a logistic regression model. We then generated predicted probabilities and classified individuals as diabetic or non-diabetic, which allowed us to compare predicted versus actual outcomes through a confusion matrix. This model lets us to assess how each risk factor influences the likelihood of developing diabetes while accounting for the others.</p>
<p>We then created a classification tree with the same predictors to see how the variables split the data and which factors were most relevant for prediction. This tree is a simple graphical representation of the decision criteria that distinguish diabetics from non-diabetics. Together, these steps allows us to evaluate both statistical significance and prediction accuracy for diabetes risk.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = diabetes ~ BMXBMI + SBP_mean + DBP_mean + LBXGH + 
    LBXTC + smoker_ever, family = "binomial", data = log_r2)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -13.384834   0.727232 -18.405  &lt; 2e-16 ***
BMXBMI        0.045553   0.008362   5.448 5.10e-08 ***
SBP_mean      0.018959   0.003937   4.816 1.47e-06 ***
DBP_mean     -0.036323   0.006810  -5.334 9.61e-08 ***
LBXGH         2.175551   0.090864  23.943  &lt; 2e-16 ***
LBXTC        -0.015141   0.001587  -9.541  &lt; 2e-16 ***
smoker_ever   0.122853   0.120768   1.017    0.309    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3983.3  on 4985  degrees of freedom
Residual deviance: 2009.4  on 4979  degrees of freedom
AIC: 2023.4

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted    0    1
        0 4247  271
        1   56  412</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tree' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="results_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The logistic regression results demonstrate that HbA1c (LBXGH) is the most powerful predictor of diabetes, with a large and highly significant coefficient (2.1755). BMI, systolic blood pressure, and cholesterol are all significant predictors of diabetes, but smoking status is not. The confusion matrix demonstrates that the model performs well overall: it properly categorised 4,247 non-diabetic individuals and 412 diabetic individuals, with just 271 false negatives and 56 false positives. With an accuracy of 93%. This suggests that the model can reasonably differentiate between diabetic and non-diabetic patients.</p>
<p>The tree also demonstrates that HbA1c is the main variable which splits the individuals into diabetic or non diabetic groups. If the A1c (blood glucose/sugar) value is less than 5.7, it is normal, but if it is greater than 6.5, the person is diabetic [4].</p>
<p><strong>(iii)</strong> In our third and final research question, we try to find if we can properly classify individuals into high vs low metabolic risk groups. To answer this question we created a new variable “high_risk”. Indivizuals were going to be labeled high risk if they met the clinical points. That is, if their :</p>
<ul>
<li><p>AC1 levels (blood glucose levels, LBXGH) were 5.7 or higher [4];</p></li>
<li><p>BMI levels (BMXMBI levels) were 30 or higher [3];</p></li>
<li><p>Systolic blood pressure (SBP_mean) were 130 or higher [5];</p></li>
<li><p>Total Cholesterol levels ( LBXTC) were 200 or higher [6].</p>
<p>We then chose the relevant predictors and used a logistic regression model to determine what factors predicted a high metabolic risk strongly. We also built a confusion matrix to assess how effectively the model predicted high- and low-risk individuals. Finally, we trained a random forest model to compare results and see whether a more flexible model increases prediction accuracy.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = high_risk ~ BMXBMI + SBP_mean + DBP_mean + LBXGH + 
    LBXTC + smoker_ever, family = "binomial", data = nhanes_rq3)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -38.267231   1.347063 -28.408   &lt;2e-16 ***
BMXBMI        0.310497   0.014172  21.909   &lt;2e-16 ***
SBP_mean      0.079326   0.005235  15.154   &lt;2e-16 ***
DBP_mean     -0.017255   0.007484  -2.306   0.0211 *  
LBXGH         2.845993   0.150698  18.885   &lt;2e-16 ***
LBXTC         0.042748   0.001912  22.355   &lt;2e-16 ***
smoker_ever   0.272456   0.109407   2.490   0.0128 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5189.7  on 5223  degrees of freedom
Residual deviance: 2363.2  on 5217  degrees of freedom
AIC: 2377.2

Number of Fisher Scoring iterations: 7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted    0    1
        0  696  202
        1  335 3991</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'randomForest' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>randomForest 4.7-1.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type rfNews() to see new features/changes/bug fixes.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'randomForest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    margin</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = factor(high_risk) ~ BMXBMI + SBP_mean +      DBP_mean + LBXGH + LBXTC + smoker_ever, data = nhanes_rq3,      ntree = 200, mtry = 3) 
               Type of random forest: classification
                     Number of trees: 200
No. of variables tried at each split: 3

        OOB estimate of  error rate: 0%
Confusion matrix:
     0    1 class.error
0 1031    0           0
1    0 4193           0</code></pre>
</div>
</div>
<p>The logistic regression results indicates that all clinical factors are strong predictors of metabolic risk, particularly HbA1c, cholesterol, BMI and systolic blood pressure. All predictors had significant p-values(p&lt;0.001), suggesting they do help identify individuals at high metabolic risk.</p>
<p>The confusion matrix also shows that the logistic model performs effectively, correctly identifying 696 low-risk and 3991 high-risk people, with only small misclassification in the low-risk group. This indicates that the model is very good at detecting high-risk individuals but less accurate for low-risk ones. The random forest model also performs extraordinarily well, with an error rate of 0%, indicating that it correctly identified all individuals in this sample.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>After answering all the three research questions, our analysis showed that health factors such as BMI, HbA1c, blood pressure and cholesterol levels are very strong predictors of diabetes and overall metabolic risk. We were able to prove that BMI played a role in the prevalence of diabetes. Using a multivariable logistic model for diabetes prediction helps us analyse that HbA1c is the most influential predictor. The model not only performed well but also had an accuracy of 93%. The high and low risk classification model also showed a great performance as it achieved perfect accuracy.</p>
<p><em>NOTE: The random forest model has a 0% error rate since the high-risk variable was created with the same variables as the model (HbA1c, BMI, blood pressure, and cholesterol). Because these clinical cutoffs establish risk status, the random forest could exactly reproduce this rule. This outcome shows overfitting, rather than real prediction performance on unknown data.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>